<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.abdulhaseeb22</groupId>
        <artifactId>spring-mcp-server</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>spring-mcp-core</artifactId>
    <name>spring-mcp-core</name>
    <description>MCP core runtime logic</description>

    <dependencies>
        <dependency>
            <groupId>io.github.abdulhaseeb22</groupId>
            <artifactId>spring-mcp-annotations</artifactId>
        </dependency>

        <!-- Minimal Spring Context for core abstractions -->
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>